/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPortForm: typeof import('./../Features/PortForwarding/Components/AddPortForm.vue')['default']
    AsideMenuBar: typeof import('./../Core/App/Components/Shared/AsideMenuBar.vue')['default']
    DialogClose: typeof import('reka-ui')['DialogClose']
    DialogContent: typeof import('reka-ui')['DialogContent']
    DialogDescription: typeof import('reka-ui')['DialogDescription']
    DialogOverlay: typeof import('reka-ui')['DialogOverlay']
    DialogPortal: typeof import('reka-ui')['DialogPortal']
    DialogRoot: typeof import('reka-ui')['DialogRoot']
    DialogTitle: typeof import('reka-ui')['DialogTitle']
    DialogTrigger: typeof import('reka-ui')['DialogTrigger']
    MainLayout: typeof import('./../Core/App/Components/Layout/MainLayout.vue')['default']
    PortTable: typeof import('./../Features/PortForwarding/Components/PortTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeProvider: typeof import('./../Features/Theme/Components/ThemeProvider.vue')['default']
    WindowControls: typeof import('./../Core/App/Components/Shared/WindowControls.vue')['default']
  }
}
